# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tap < Formula
  desc ""
  homepage "https://github.com/spectre10/tap"
  version "0.1.1"

  on_macos do
    url "https://github.com/spectre10/test-go/releases/download/v0.1.1/test-go_0.1.1_darwin_all.tar.gz"
    sha256 "00e9eca1ccb27a80a0ed5a90b8b24ada24082c1435b88597e61f4454adc61cda"

    def install
      bin.install "test-go"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/spectre10/test-go/releases/download/v0.1.1/test-go_0.1.1_linux_arm64.tar.gz"
      sha256 "2fc5dc617b166356dc755228de387d9bd9ff7ba22dba338e65fce3892de7fc54"

      def install
        bin.install "fileshare-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/spectre10/test-go/releases/download/v0.1.1/test-go_0.1.1_linux_amd64.tar.gz"
      sha256 "cfd334f0bf408263a833d21d8b6432b41eab1f5f2a870898b42b4c0d75c0997b"

      def install
        bin.install "fileshare-cli"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/spectre10/test-go/releases/download/v0.1.1/test-go_0.1.1_linux_armv6.tar.gz"
      sha256 "ab1e18e9d98dae1364cfff9ed8501fb08342a8fdf0e58860638dc9a4b6b4217b"

      def install
        bin.install "fileshare-cli"
      end
    end
  end
end
