# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TestGo < Formula
  desc ""
  homepage "https://github.com/spectre10/tap"
  version "0.1.2"

  on_macos do
    url "https://github.com/spectre10/test-go/releases/download/v0.1.2/test-go_0.1.2_darwin_all.tar.gz"
    sha256 "dcd3d72353b53100251bf49df02efaa9345d0cdccf4c9f1bd860b17b23466c2f"

    def install
      bin.install "test-go"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/spectre10/test-go/releases/download/v0.1.2/test-go_0.1.2_linux_arm64.tar.gz"
      sha256 "bf59ab63e224e095b0195a1efc0afbf9fe4fe77efa16584793dcbf447191b463"

      def install
        bin.install "test-go"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/spectre10/test-go/releases/download/v0.1.2/test-go_0.1.2_linux_amd64.tar.gz"
      sha256 "560f20fb530b1fa4f70d7ddc46beb33de36b8a92821b2dc1867d44ac544fed88"

      def install
        bin.install "test-go"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/spectre10/test-go/releases/download/v0.1.2/test-go_0.1.2_linux_armv6.tar.gz"
      sha256 "5d0a3575cc5fae729addf42a521c802071fde5f3d93e54fe413b6b4e0c3342ce"

      def install
        bin.install "test-go"
      end
    end
  end
end
