# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TestGo < Formula
  desc ""
  homepage "https://github.com/spectre10/test-go"
  version "0.1.3"

  on_macos do
    url "https://github.com/spectre10/test-go/releases/download/v0.1.3/test-go_0.1.3_darwin_all.tar.gz"
    sha256 "e0ad60e97835d65191656be4d97f213c0d59ca8d664f6b1e773a876b44a75447"

    def install
      bin.install "test-go"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/spectre10/test-go/releases/download/v0.1.3/test-go_0.1.3_linux_arm64.tar.gz"
      sha256 "7e06d83de6e06a087861d5ca8539830cdeae23c3e3d18d52115bc9201e4bf720"

      def install
        bin.install "test-go"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/spectre10/test-go/releases/download/v0.1.3/test-go_0.1.3_linux_amd64.tar.gz"
      sha256 "a2436c6d969468be9dedc2ac9a2b95699a73636d639bf82ea152f1fd5bdb014b"

      def install
        bin.install "test-go"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/spectre10/test-go/releases/download/v0.1.3/test-go_0.1.3_linux_armv6.tar.gz"
      sha256 "b9e5ee4123998cfdcbbdd3416ac92e75e2601f9b2074138e96046c61fc94f791"

      def install
        bin.install "test-go"
      end
    end
  end
end
